### ISSUE TITLE
Thank you

### ISSUE THREAD

**Issue by VisualFox** [brandonmpetty/Doxa#6]
Just wanted to let you know that I really appreciate your work. I like the new additions, and the general code structure. Performance is now really good and ISauvola give me some nice results (as a low hanging fruit I tried IWolf and IWan they work great too).

I am currently testing Doxa with via a javascript frontend (Doxa is compiled into Webassembly with emscripten) and everything is running great. If you are interested I will be happy to show you more of that or setup a small demo.

Unfortunately as I cannot find a way to send you a Private Message I am abusing the Github issues system, I hope that ok.

**Comment by brandonmpetty** [comment]
It was great talking with you.  You inspired me to look into WebAssembly.  I created a test branch for it and have it running through GitHub Pages: https://brandonmpetty.github.io/Doxa/WebAssembly

I am ironically only having issues with the ISauvola algorithm in WebAssembly... which is a shame because I agree with you that it is probably the best one.  I wish the debugging capabilities were better.  I would be interested in any recommendations you have for exposing this library through JavaScript / WASM.

Also, I have added my email address to my gh bio.  When I get a non-work address that I actually check I will enable the regular contact options.  Thanks again Philippe!
